### ISSUE TITLE
CLI errors; nomnom belongs in dependencies rather than devDependencies

### ISSUE THREAD

**Issue by mt-caret** [Khan/KaTeX#1216]
Since cli.js depends on nomnom but is listed in devDependencies, katex installed in the usual manner (ex. `yarn global add katex`) fails with an error about a missing module.

```bash
$ katex --help
module.js:559
    throw err;
    ^
Error: Cannot find module 'nomnom'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/delta/.config/yarn/global/node_modules/katex/cli.js:9:17)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
```

**Comment by edemaine** [comment]
@mt-caret Thanks for the report.  I keep forgetting that `cli.js` exists!  It could use some added command-line options to match new settings too.
