### ISSUE TITLE
cli doesn't run after yarn global install

### ISSUE THREAD

**Issue by shaunc** [Khan/KaTeX#1229]
After

    yarn global add khan/katex

I get:
```
Error: Cannot find module './'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/shauncutts/.config/yarn/global/node_modules/katex/cli.js:6:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```
which is unsurprising as there is no "index.js" in the package root (?)

**Comment by kevinbarabash** [comment]
Good call. cli.js should probably be updated to include `"./dist/katex.js"` instead of `"./"`.  We should probably have some tests for cli.js as well.

**Comment by shaunc** [comment]
thanks!

**Comment by edemaine** [comment]
I figured out part of the problem: `yarn global add khan/katex` makes a `yarn/global/node_modules/katex` directory *without* `dist`.  This causes the `./` -> `dist/katex.js` pointer (specified by property `main` in `package.json`) fail.

But I can't figure out why `yarn` would differ from `npm` in this way.  Anyone have ideas?

**Comment by ylemkimon** [comment]
`khan/katex` resolves to this GitHub repository and clones the master branch, which doesn't contain built files. (https://github.com/Khan/KaTeX/issues/894#issuecomment-404758297) You should grab release version from npm, i.e., `yarn global add katex`. (If you'd like to use development version, see previous comment and `CONTRIBUTING.md` for how to build the prokect)

**Comment by shaunc** [comment]
Thanks!
