### ISSUE TITLE
Local website not building

### ISSUE THREAD

**Issue by ronkok** [Khan/KaTeX#1632]
After successfully running `yarn build` at the root, I ran `cd website` and `yarn start`. The result was:

```
Error: Cannot find module 'remarkable-embed'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by ylemkimon** [comment]
You should install the dependencies for the website separately, at least for now.

**Comment by ronkok** [comment]
@ylemkimon Thank you. That did the trick.
