### ISSUE TITLE
Issue parsing (-1*12*a) @0.5.1

### ISSUE THREAD

**Issue by gaye** [Khan/KaTeX#442]
> katex.renderToString('\\left(-1\\cdot12\\cdota\̲\right)')
ight)Error: KaTeX parse error: Expected '\right', got '\cdota' at position 21: -1\cdot12\cdota̲̲
    at new ParseError (/home/gareth/Documents/mathleap/node_modules/katex/src/ParseError.js:29:16)
    at Parser.expect (/home/gareth/Documents/mathleap/node_modules/katex/src/Parser.js:76:15)
    at Parser.parseImplicitGroup (/home/gareth/Documents/mathleap/node_modules/katex/src/Parser.js:417:14)
    at Parser.parseAtom (/home/gareth/Documents/mathleap/node_modules/katex/src/Parser.js:302:21)
    at Parser.parseExpression (/home/gareth/Documents/mathleap/node_modules/katex/src/Parser.js:147:25)
    at Parser.parseInput (/home/gareth/Documents/mathleap/node_modules/katex/src/Parser.js:114:27)
    at Parser.parse (/home/gareth/Documents/mathleap/node_modules/katex/src/Parser.js:105:22)
    at parseTree (/home/gareth/Documents/mathleap/node_modules/katex/src/parseTree.js:14:19)
    at Object.renderToString (/home/gareth/Documents/mathleap/node_modules/katex/katex.js:52:16)
    at repl:1:7

It seems like KaTeX only expects parens around a single `operand operator operand` and that here we have `operand operator operand operator operand` within parens. Or is the input otherwise invalid?

**Comment by xymostech** [comment]
you need a space in between `cdot` and `a`. it is complaining that `\cdota` is not a command.

**Comment by gaye** [comment]
Thanks @xymostech!
