### ISSUE TITLE
EOF error with overrightarrow & superior/inferior

### ISSUE THREAD

**Issue by jbg77** [Khan/KaTeX#532]
Hello, 

I have an error with parsing to string, the overrightarrow & superior/inferior don't work:

```
Exception while invoking method 'createPDF' ParseError: KaTeX parse error: Expected 'EOF', got '\overrightarrow' at position 15: \overrightarrow̲{grad}V=\frac{
    at new ParseError (/bundle/bundle/programs/server/npm/node_modules/katex/src/ParseError.js:29:16)
    at Parser.expect (/bundle/bundle/programs/server/npm/node_modules/katex/src/Parser.js:76:15)
    at Parser.parseInput (/bundle/bundle/programs/server/npm/node_modules/katex/src/Parser.js:116:10)
    at Parser.parse (/bundle/bundle/programs/server/npm/node_modules/katex/src/Parser.js:105:22)
    at parseTree (/bundle/bundle/programs/server/npm/node_modules/katex/src/parseTree.js:14:19)
    at Object.renderToString (/bundle/bundle/programs/server/npm/node_modules/katex/katex.js:52:16)
```

```
Exception while invoking method 'createPDF' ParseError: KaTeX parse error: Expected 'EOF', got '&' at position 30: V}{\partial r}&̲lt;0
    at new ParseError (/bundle/bundle/programs/server/npm/node_modules/katex/src/ParseError.js:29:16)
    at Parser.expect (/bundle/bundle/programs/server/npm/node_modules/katex/src/Parser.js:76:15)
    at Parser.parseInput (/bundle/bundle/programs/server/npm/node_modules/katex/src/Parser.js:116:10)
    at Parser.parse (/bundle/bundle/programs/server/npm/node_modules/katex/src/Parser.js:105:22)
    at parseTree (/bundle/bundle/programs/server/npm/node_modules/katex/src/parseTree.js:14:19)
    at Object.renderToString (/bundle/bundle/programs/server/npm/node_modules/katex/katex.js:52:16)
```

How can I fix it ?

Thank in advance

**Comment by kevinbarabash** [comment]
@jbg77 we don't support `\overrightarrow`.  Can you post the rest of the TeX code that you're trying to parse?

**Comment by kevinbarabash** [comment]
@jbg77 you might be interested in https://github.com/Khan/KaTeX/pull/524.

**Comment by jbg77** [comment]
I will look that

The code is simply `\frac{\partial V}{\partial r} < 0`

Thank you by the way :)

**Comment by gagern** [comment]
If your input to KaTeX contains HTML entities, you have to either change the way you obtain that input so that they don't get escaped or you read them from the DOM after they have been handled. Or you have to add a string rewrite step of your own to undo the html entity escaping. This is essentially outside the core of KaTeX, but depends on the glue you use to feed KaTeX its input.

**Comment by kevinbarabash** [comment]
Support for é, è, etc is on master.  For < and > use `\lt` and `\gt`.  @jbg77 in the title of this issue you mentioned `superior`/`inferior`, are you referring to `\sup` and `\inf`?

**Comment by kevinbarabash** [comment]
Support for `\overrightarrow` was added in [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0).
